/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export function Model(props) {
  const { nodes, materials } = useGLTF("./src/assets/Lobster.gltf");
  const myMesh = useRef();

  useFrame((state, delta) => (myMesh.current.rotation.x += delta));
  useFrame((state, delta) => (myMesh.current.rotation.y += (delta / 2)));
  useFrame((state, delta) => (myMesh.current.rotation.z += delta));

  return (
    <group {...props} dispose={null} ref={myMesh}>
      <group position={[0, 0.06, 0]} rotation={[-Math.PI, 0.65, -Math.PI]}>
        <group position={[-0.03, 0.03, 0.03]} rotation={[0.17, 0, 0]}>
          <group position={[0, 0, 0.22]} rotation={[-0.17, 0, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["828418ae-409d-ec78-05e6-965d62d45c6e"].geometry}
              material={materials.lobay}
              position={[0, -0.03, -0.31]}
            />
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["787d4ade-b0b2-15ad-4dc1-703f5e9b3b96"].geometry}
            material={materials.lobay}
            position={[0.03, -0.03, -0.03]}
          />
        </group>
        <group position={[-0.02, 0.03, 0.07]} rotation={[0, 0.26, 0]}>
          <group position={[0.07, 0, -0.18]} rotation={[0.18, -0.3, 0.05]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["764d556b-ba4d-f29a-e1c6-41bf68727abc"].geometry}
              material={materials.lobay}
              position={[-0.02, 0, 0.02]}
              rotation={[0, 0.65, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["2674b917-5a13-9c21-bd79-0b90cf7c07f7"].geometry}
              material={materials.lobay}
              position={[0.12, -0.03, -0.18]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["6c42211a-aa4c-0898-287e-b373ff02b30c"].geometry}
              material={materials.boop}
              position={[0.07, 0, -0.24]}
              rotation={[0, -0.74, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["e40932e6-f92c-aa73-3c76-e76da71ee50c"].geometry}
              material={materials.boop}
              position={[0.06, 0, -0.28]}
              rotation={[0, 0.61, 0]}
            />
          </group>
          <group position={[-0.1, 0, -0.18]} rotation={[0.27, 0.29, -0.08]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["cc345066-852e-7f02-8be5-2eaea2c111ac"].geometry}
              material={materials.lobay}
              position={[0.02, 0, 0.02]}
              rotation={[0, -0.65, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["3ed6b626-9b82-b983-0772-7f7ebbee29d7"].geometry}
              material={materials.lobay}
              position={[-0.12, -0.03, -0.18]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["66a55f38-0b3d-59d8-db6d-5dcb301a2f4f"].geometry}
              material={materials.boop}
              position={[-0.07, 0, -0.24]}
              rotation={[0, 0.74, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["3e749433-0833-818b-5d48-7e82a5ad3269"].geometry}
              material={materials.boop}
              position={[-0.06, 0, -0.28]}
              rotation={[0, -0.61, 0]}
            />
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["659e901c-56e7-2b5f-0e5a-1c0d18e7be1d"].geometry}
            material={materials.lobay}
            position={[0.02, -0.03, -0.07]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["6b8f7b63-89bb-d301-cbb5-78ec05574c7b"].geometry}
            material={materials.lobay}
            position={[-0.1, -0.08, -0.04]}
            rotation={[0, 0, 0.87]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["39a06f1b-8078-986b-4375-4e34e0f37c57"].geometry}
            material={materials.lobay}
            position={[0.08, -0.08, -0.04]}
            rotation={[0, 0, -0.87]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/Lobster.gltf");
